# Generated by Django 4.2.1 on 2023-07-19 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='data',
            field=models.DateField(auto_now_add=True, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='nomeDoPet',
            field=models.CharField(max_length=50, verbose_name='Nome do PET'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='observacoes',
            field=models.TextField(blank=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='tamanho',
            field=models.IntegerField(choices=[(0, 'Pequeno'), (1, 'Médio'), (2, 'Grande')], verbose_name='Tamanho'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='telefone',
            field=models.CharField(max_length=15, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='turno',
            field=models.CharField(choices=[('manha', 'Manhã'), ('tarde', 'Tarde')], max_length=5, verbose_name='Turno'),
        ),
    ]
