# Generated by Django 4.2.1 on 2023-07-19 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0002_alter_reserva_data_alter_reserva_nomedopet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='data',
            field=models.DateField(verbose_name='Data'),
        ),
    ]
