# Generated by Django 4.0.6 on 2023-09-20 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0007_categoriaanimal_alter_reserva_petshop_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='categoria_animal',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='reserva.categoriaanimal', verbose_name='Categoria do Animal'),
        ),
    ]
